[package]
name = "ropey_regex"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aho-corasick = "1.0.2"
memchr = "2.5.0"
regex-automata = { version =  "0.3.1", path = "../regex/regex-automata"}
regex-syntax = "0.7.4"
ropey = "1.6.0"

[dev-dependencies]
proptest = "1.2.0"
