[package]
name = "ropey_regex"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memchr = "2.6"
regex-automata = { version =  "0.4.2", path = "../regex/regex-automata" }
regex-syntax = "0.8.2"
ropey = "1.6.0"

[dev-dependencies]
proptest = "1.2.0"

[features]
default = ["perf-inline"]
perf-inline = []
