use_small_heuristics = "Max"
newline_style = "Unix"
use_field_init_shorthand = true

imports_granularity = "Module"
group_imports = "StdExternalCrate"
format_macro_matchers = true
format_macro_bodies = true
